### ISSUE TITLE
Remove use of thread-local storage

### ISSUE THREAD

**Issue by mizdebsk** [kjn/nosync#3]
nosync uses `__thread` TLS. When it is built on Fedora 27 ppc64le, GCC adds reference to `__tls_get_addr_opt` symbol, which is only available since GLIBC_2.22. This prevents nosync compiled on Fedora 27 from working on RHEL 7, as RHEL 7 has only glibc-2.17.

CC @clime

**Comment by clime** [comment]
Yes, thx. This would be cool to be solved. We like using nosync for building but currently we can't on ppc64le due to this problem.

**Comment by mizdebsk** [comment]
@clime `nosync-1.1-1.fc27`, which includes the fix, is now available in `f27-infra` repo. I tested it on https://fedorainfracloud.org/ with `copr-builder-ppc64le-f27` image and it seems to fix the issue.

**Comment by clime** [comment]
It works now for epel-7-ppc64le (and all the other chroots as well). Thank you for the quick fix!
